name: open-agar

services:
  webserver:
    image: node:23-alpine
    build: ./webserver
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep -q 3001"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
  bot:
    image: python:3
    build: ./bot
    depends_on:
      webserver:
        condition: service_healthy